name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode resume.tex

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Nima Nourinejad'
        git config --global user.email 'nima.nourinejad@gmail.com'
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        cp resume.pdf ./resume.pdf
        git add resume.pdf
        git commit -m "Update resume" || echo "No changes to commit"
        git push origin gh-pages
