name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode resume.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'Nima Nourinejad'
        git config --global user.email 'nima.nourinejad@gmail.com'
        git fetch origin
        git checkout gh-pages
        cp resume.pdf ./resume.pdf
        git add resume.pdf
        git commit -m "Update resume"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
