name: Update Resume on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX Document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error resume.tex
      continue-on-error: false

    - name: Verify PDF Generation
      run: ls -l resume.pdf
      continue-on-error: true

    - name: Check for PDF Existence
      run: test -f resume.pdf && echo "resume.pdf exists" || echo "resume.pdf does not exist"
      continue-on-error: true

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Nima Nourinejad'
        git config --global user.email 'nima.nourinejad@gmail.com'
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        cp resume.pdf ./resume.pdf
        git add resume.pdf
        git commit -m "Update resume" || echo "No changes to commit"
        git push origin gh-pages
      continue-on-error: true
