name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex   # Specify the main LaTeX document

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode resume.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: resume
        path: ./resume.pdf
